trigger:
- master

variables:
  UE_ROOT: 'D:\UKHO\Unreal Engine\UE_5.3'  # Confirm this path matches your installation
  PROJECT_PATH: '$(Build.SourcesDirectory)\TestCICD.uproject'
  BUILD_DIR: '$(Build.ArtifactStagingDirectory)\Build'
  PACKAGE_DIR: '$(Build.ArtifactStagingDirectory)\Package'

pool: unrealengine

stages:
- stage: pixel_streaming
  displayName: Enable Pixel Streaming
  jobs:
  - job: enable_pixel_streaming
    steps:
    - script: |
        echo "Building Unreal Project..."
        "%UE_ROOT%\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
          -project="%PROJECT_PATH%" ^
          -noP4 ^
          -platform=Win64 ^
          -clientconfig=Development ^
          -serverconfig=Development ^
          -cook ^
          -iterativecooking ^
          -allmaps ^
          -build ^
          -stage ^
          -pak ^
          -compressed ^
          -archive ^
          -archivedirectory="%BUILD_DIR%"
      displayName: 'Build Project'
    - script: |
        echo "Packaging for Production..."
        "%UE_ROOT%\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
          -project="%PROJECT_PATH%" ^
          -noP4 ^
          -platform=Win64 ^
          -clientconfig=Shipping ^
          -serverconfig=Shipping ^
          -build ^
          -stage ^
          -pak ^
          -archive ^
          -archivedirectory="%PACKAGE_DIR%" ^
          -skipcook
      displayName: 'Package Project'

  

