trigger:
- master

variables:
  UE_ROOT: 'D:\UKHO\Unreal Engine\UE_5.3'  # Confirm this path matches your installation
  PROJECT_PATH: '$(Build.SourcesDirectory)\TestCICD.uproject'
  BUILD_DIR: '$(Build.ArtifactStagingDirectory)\Build'
  PACKAGE_DIR: '$(Build.ArtifactStagingDirectory)\Package'

pool: unrealengine

stages:
- stage: pixel_streaming
  displayName: Enable Pixel Streaming
  jobs:
  - job: enable_pixel_streaming
    steps:
    - task: UseDotNet@2
      displayName: 'Install .net framework 8'
      inputs:
        packageType: 'runtime'
        version: '8.0.x'
        includePreviewVersions: false
        
    - script: |
        "%UE_ROOT%\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.exe" -Mode=Json -PluginAction=Enable -Project="%PROJECT_PATH%" -Plugin="PixelStreaming"
      displayName: 'Enable Pixel Streaming Plugin'
      name: EnablePluginStep