trigger:
  - master

variables:
  UE_ROOT: 'D:\UKHO\Unreal Engine\UE_5.3'
  PROJECT_PATH: '$(Build.SourcesDirectory)\TestCICD.uproject'
  PROJECT_NAME: "TestCICD"
  BUILD_DIR: "$(Build.BinariesDirectory)"
  PACKAGE_DIR: "$(Build.ArtifactStagingDirectory)\Package"

stages:
  - stage: BuildCookPackage
    pool: unrealengine
    displayName: Build, Cook, and Package
    jobs:
      - job: build_project
        displayName: "Build and Ship Package"
        steps:
          - script: |
              echo "Building Unreal Project..."
              "%UE_ROOT%\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
                -project="%PROJECT_PATH%" ^
                -noP4 ^
                -platform=Win64 ^
                -clientconfig=Development ^
                -serverconfig=Development ^
                -cook ^
                -iterativecooking ^
                -allmaps ^
                -build ^
                -stage ^
                -pak ^
                -compressed ^
                -archive ^
                -archivedirectory="%BUILD_DIR%"
            displayName: Building the project

          - script: |
              echo "Packaging for Production..."
              "%UE_ROOT%\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
                -project="%PROJECT_PATH%" ^
                -noP4 ^
                -platform=Win64 ^
                -clientconfig=Shipping ^
                -serverconfig=Shipping ^
                -build ^
                -stage ^
                -pak ^
                -archive ^
                -archivedirectory="%PACKAGE_DIR%" ^
                -skipcook
            displayName: Building Shipping Package

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(PACKAGE_DIR)\Windows\*' # Adjust based on output
              archiveType: "zip"
              archiveFile: '$(Build.ArtifactStagingDirectory)\$(PROJECT_NAME).zip'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)\\$(PROJECT_NAME).zip"
              ArtifactName: "drop"
              publishLocation: "Container"

  - stage: DevDeploy
    pool: unrealengine-dev
    dependsOn: BuildCookPackage
    displayName: "Deploy to Dev environment"
    jobs:

      - job: DevDeploy
        displayName: "Deploy to dev"
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              artifactName: "drop"
              downloadPath: "$(Build.ArtifactStagingDirectory)"

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: "$(Build.ArtifactStagingDirectory)\\$(PROJECT_NAME).zip"
              destinationFolder: "C:\\$(PROJECT_NAME)"
              cleanDestinationFolder: true # This ensures the target folder is emptied before extraction
              overwriteExistingFiles: true # Ensures old files are replaced
